before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://jukkacle:$GITHUB_API_KEY@github.com/jukkacle/raspberrypi-command-execute --tags

after_success: 
- chmod +x ./upload-apk.sh
- sh ./upload-apk.sh 

branches:
  except:
    - /^*-v[0-9]/
    
language: android

android:
    components:
    - build-tools-25.0.0
    - platform-tools
    - tools
    - android-25

env:
  - ANDROID_HOME=/usr/local/android-sdk

